a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É uma letra? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Está em maiusculas? ', a.isupper())
print('Está em minusculas? ', a.islower())
print('É decimal? ', a.isdecimal())
print('Éstá captalizado? ', a.istitle())